### PR TITLE
Clarify `std::async` policy behavior

### PR DESCRIPTION
**Pull request by Mq-b**
Update async policy description to align with C++ standard and clarify Microsoft implementation

- Modified the description of `launch::async` policy to reflect that the C++ standard states the function behaves as if it invokes the callable object in a new thread.
- Clarified that the Microsoft implementation uses the Windows ThreadPool, which may provide recycled threads, resulting in behavior equivalent to `launch::async|launch::deferred`.
- Added a note about the implications for thread-local variables, recommending against their use with `async`.

This update ensures the documentation accurately reflects both the C++ standard and the specifics of the Microsoft implementation.

References:
- https://eel.is/c++draft/futures.async
- https://en.cppreference.com/w/cpp/thread/launch

### CODE REVIEW

**Comment by Mq-b** [comment]
I think the main thing is that C++ doesn't specify:

> The C++ standard states that if policy is launch::async, the function creates a new thread.

**Comment by Court72** [comment]
@TylerMSFT

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by StephanTLavavej — APPROVED** [review]

**Review by TylerMSFT — APPROVED** [review]
Thank you

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
