### PR TITLE
Add documentation for experimental warning: C6389

### PR DESCRIPTION
**Pull request by Xazax-hun**
This warning will be part of the next major VS release.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@Xazax-hun : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@Xazax-hun : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@corob-msft Could you review the new article proposal? We can move the commit to the private repo if you would like to add it. Thanks.

**Comment by corob-msft** [comment]
@ktoliver 
Yes, thanks, I'd appreciate a move to cpp-docs-pr to facilitate Acrolinx and preview. I need to make an edit pass, too.

**Comment by ktoliver** [comment]
@corob-msft It's on my to-do list for tomorrow morning. 👍🏻 I'll post here when finished and then close this pull request. Thanks.

**Comment by ktoliver** [comment]
The commit is now in a new pull request in the public repo, where it will be merged. The contributor association will be maintained. We'll close this pull request. Thanks.

**Pull request closed without merging**
