### PR TITLE
Fix excess closing square bracket typo

### PR DESCRIPTION
**Pull request by Rageking8**

### CODE REVIEW

**Comment by Court72** [comment]
@TylerMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — APPROVED** [review]
Thanks, @rageking

**Comment by TylerMSFT** [comment]
#sign-off

**Comment by TylerMSFT** [comment]
@rageking8 - It seems impersonal to always refer to you as 'rageking8' What's your name?

**Comment by Rageking8** [comment]
> @rageking8 - It seems impersonal to always refer to you as 'rageking8' What's your name?

Hi @TylerMSFT, I would prefer to keep it as status quo (i.e. to continue using my GH username for all purposes). Thanks!

**Pull request merged**
