### PR TITLE
fix the format in issue #1697

### PR DESCRIPTION
**Pull request by mstva**
as in the issue #1697, I did the following: 
in the edit code section, the format was "a+b | a-b | a*b | a/b" and I added spaces to become "a + b | a - b | a * b | a / b"

### CODE REVIEW

**Comment by PRMerger16** [comment]
@Mstava : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@corob-msft - This looks good to me; is it OK to merge? 

Thanks.

**Comment by corob-msft** [comment]
@ktoliver
Unfortunately, this PR only changes one of six places this string appears in code blocks, and it also appears in a screenshot, which would have to be recreated to match. There's nothing wrong with the proposal, but the implementation requires extra work. The submitter did not make their fork editable, so we can't do the work in this PR. Perhaps the PR is best closed, and our planned rewrite of this material can pick up such changes. Apologies to @mstva ; Thanks for seeing a need and attempting to fix it.

**Comment by ktoliver** [comment]
Alright, thanks @corob-msft

**Pull request closed without merging**
