### PR TITLE
Edit Assignment article

### PR DESCRIPTION
**Pull request by oboukli**
Clean up example code
Add note on copy assignment operator
Add note on the Rule of Three with link to Wikipedia
Update See Also section
Fix Markdown lint issues
Clean up and trim white spaces

### CODE REVIEW

**Comment by PRMerger20** [comment]
@oboukli : Thanks for your contribution! The author, @mikeblome, has been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@oboukli : Thanks for your contribution! The author, @mikeblome, has been notified to review your proposed change.

**Comment by oboukli** [comment]
Note: due to trimmed redundant white spaces, it might be helpful to turn on the _Hide whitespace changes_ option of GitHub diff editor. Also, using the _rich diff_ option can be helpful.

**Comment by mikeblome** [comment]
Thanks @oboukli . Good comment to add.

**Pull request merged**
