### PR TITLE
Add docs for turn on /PROFILE linker option within CMake project

### PR DESCRIPTION
**Pull request by dcnoway**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@dcnoway : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by TrishaMc** [comment]
@corob-msft - Would you review the proposed changes? Thanks.

**Comment by mikeblome** [comment]
#hold-off
I've got this one.

**Comment by PRMerger17** [comment]
@mikeblome : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Pull request merged**
