### PR TITLE
Update windows-store-apps-the-windows-runtime-and-the-c-run-time.md

### PR DESCRIPTION
**Pull request by Jaiganeshkumaran**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@Jaiganeshkumaran : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by TylerMSFT — CHANGES_REQUESTED** [review]
Thank you for contributing to the docs. We appreciate that.
I think the change for Windows 8 or greater is good.
Could you modify the second change, because it's not grammatically correct. I think it's better to say "UWP apps don't support the following CRT features"

**Comment by PRMerger9** [comment]
@Jaiganeshkumaran : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by TylerMSFT — APPROVED** [review]
@Jaiganeshkumaran , thank you for taking an interest in the docs and helping improve them.

**Pull request merged**
