### PR TITLE
Add that "g" has been deprecated

### PR DESCRIPTION
**Pull request by EddieBreeveld**
I'm not sure how to refer to the relevant web page, I've just added the link.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@EddieBreeveld : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by corob-msft — APPROVED** [review]
@EddieBreeveld Thanks for the contribution. I think I missed this earlier because it didn't come up in a search for `Og`.

**Pull request merged**
