### PR TITLE
Add docs on using existing cache without cmake-server

### PR DESCRIPTION
**Pull request by sfreed141**
Add instructions on how to continue using existing cache after the deprecation of cmake-server in CMake 3.20

### CODE REVIEW

**Comment by PRMerger18** [comment]
@sfreed141 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by corob-msft** [comment]
@sfreed141 

Thanks for the update! I'm taking a look now, and I realized I'm unclear on whether you just have to take any one of the steps, or all of them. My proposed style edit is based on the former:

```
> [!NOTE]
> The default existing cache experience relies on `cmake-server`, which was removed from CMake in version 3.20. To continue using existing cache functionality in Visual Studio 2019 version 16.10 and later, take one of these steps:
> - Manually install CMake version 3.19 or lower. Then, set the `cmakeExecutable` property in your existing cache configuration to use that version of CMake.
> - In your existing cache configuration, set the `cacheGenerationCommand` property to let Visual Studio request the necessary CMake file-based API files. For more information, see [CMakeSettings.json reference](cmakesettings-reference.md#configurations).
> - Use a query file to request the CMake file-based API files when generating your cache before it's opened in Visual Studio. For query file instructions, see the next section, [Advanced CMake cache troubleshooting](#advanced).

### <a name="advanced"></a> Advanced CMake cache troubleshooting
```

Let me know if you see any issues here.

**Comment by PRMerger19** [comment]
@sfreed141 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by corob-msft — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
