### PR TITLE
fixed broken links for code examples

### PR DESCRIPTION
**Pull request by vedmin**
Fixed broken links for code examples of asynchronous operations in C++.

### CODE REVIEW

**Comment by Court72** [comment]
@TylerMSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by TylerMSFT** [comment]
@vedmin, Hi, thank you for caring about the docs. I'm puzzled by the change because our filesystem isn't case-sensitive and I don't see a problem with the existing links. Can you explain what you are seeing that led you to make these changes?

**Review by TylerMSFT — CHANGES_REQUESTED** [review]
Hi, these changes aren't necessary. The links aren't case-sensitive and we use lowercase.

**Comment by TylerMSFT** [comment]
Asked for clarification in November, but didn't hear back. I don't believe this change is necessary.

**Pull request closed without merging**
