### PR TITLE
Fix arm64 abi return value docs

### PR DESCRIPTION
**Pull request by sigatrev**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@sigatrev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by corob-msft** [comment]
@sigatrev Is this meant to address #2371?

**Comment by sigatrev** [comment]
> @sigatrev Is this meant to address #2371?

Yeah. It was in response to the DevCom issue about the same thing. I didn't realize the issue was opened here first - thanks for redirecting to give us visibility.

**Comment by corob-msft** [comment]
@sigatrev These changes should appear on Docs by noon tomorrow (Wednesday).

**Comment by corob-msft** [comment]
Or possibly Thursday. I think I missed a merge deadline. :(

**Pull request merged**
