### PR TITLE
fix: MD019/no-multiple-space-atx

### PR DESCRIPTION
**Pull request by nschonni**
Multiple spaces after hash on atx style heading

### CODE REVIEW

**Comment by nschonni** [comment]
@corob-msft I rebased an re-ran the automated fix

**Comment by corob-msft** [comment]
@nschonni I'm sorry about that. For some reason the merge from live didn't run earlier today - I expected automation to push it around five or six hours ago. It has what I expect are the vast majority of these fixes already applied. It might be easier to abandon this PR and re-run against the current content.

**Comment by nschonni** [comment]
no worries, keep this open and it'll rebase again

**Comment by nschonni** [comment]
@corob-msft looks like it is good now. I'll close and remove the rule from the other "disable rule" PR

**Pull request closed without merging**
