### PR TITLE
Resolve syncing conflicts from FromPrivateLiveToMaster to main

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from FromPrivateLiveToMaster to main.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@Taojunshen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by corob-msft — APPROVED** [review]

**Comment by PRMerger-2** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@corob-msft I resolved the merge conflicts in favor of the "post" updates in https://github.com/MicrosoftDocs/cpp-docs-pr/commit/f8d1a12bc48f19a073370be24e812e37227745c0# (internal link). Let's see if merging this will smooth the way for repo sync.

**Comment by corob-msft** [comment]
Thanks, @ktoliver. I approved the PR from my phone, but the merge edit was a bit much to do on a phone, so I left it for later.

**Pull request merged**
