### PR TITLE
Update how-to-convert-between-various-string-types.md

### PR DESCRIPTION
**Pull request by drvoss**
fix typo

### CODE REVIEW

**Comment by PRMerger17** [comment]
@drvoss : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
@corob-msft - Would you review the proposed changes? Thanks

**Comment by PRMerger16** [comment]
@drvoss : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@drvoss : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@drvoss : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@corob-msft : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Pull request merged**
