### PR TITLE
Updated Readme.md

### PR DESCRIPTION
**Pull request by 19ANDY**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@19ANDY : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
@corob-msft - Would you review the proposed changes? Thanks

**Comment by corob-msft** [comment]
@19ANDY Based on the link targets, I might guess this change is intended for people who come here and wonder "What is Visual Basic, anyway?" But the rest of the paragraph is about telling people that were looking for something else that it isn't here, and shows them where they can find it. That is, it's for people who know what VB and C# and VS are, and want to edit those topics instead of the C++ ones. Now a few people may come here and think "Hmm, VB, I don't know what that is, let's find out more," but I'm going to guess that's a really small number of people. And for everyone else, the links are actually a little bit of a distraction. So, I'm curious what your justification is for this change, and thus if it's worth making. Would you care to elaborate?

**Comment by corob-msft** [comment]
@19ANDY We appreciate your efforts to contribute to our content, and want to encourage it. I'm closing this PR, as I'm not convinced it's necessary, but feel free to reopen if you have additional justification.

**Pull request closed without merging**
