### PR TITLE
Fix git push error for protected CLA branch

### PR DESCRIPTION
**Pull request by fenxu**
The pull request is created from master636820509235897685 to master to fix git push error for protected CLA branch

### CODE REVIEW

**Comment by PRMerger15** [comment]
@fenxu : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by fenxu** [comment]
@corob-msft I've enabled service account for sync action, in the future, it won't use my account but service account to do sync. Please let me know if you find any problem.

**Comment by corob-msft** [comment]
Sounds good. What is the name of the account?

// Colin Robertson | docs.microsoft.com | Visual Studio | C++

________________________________

**Comment by fenxu** [comment]
It's like opbld** account. ** represents for number because we have to use a pool of service accounts to avoid GitHub Rate Limit issue.

**Comment by corob-msft** [comment]
Okay, I've added the build_service_account group, which includes all of the Opbld## accounts, to the list of accounts that have permissions to push to the master branch. Will this fix the git push error in the automation?


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by fenxu** [comment]
@corob-msft Those service accounts already have sufficient permission when provisioned the repository.

**Pull request merged**
