### PR TITLE
Mention limits of concurrency

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Mention limits of concurrency. See Microsoft/STL#2099

### CODE REVIEW

**Comment by PRMerger14** [comment]
@AlexGuteniev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@AlexGuteniev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@AlexGuteniev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@AlexGuteniev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@AlexGuteniev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@AlexGuteniev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by TylerMSFT — CHANGES_REQUESTED** [review]
Thank you, @AlexGuteniev.  I appreciate the Microsoft-specific updates.
Could you smooth the sentences out a little bit. They sound fragmentary. For example, instead of "Maximums number of chunks..." it would help if you wrote "The maximum number of chunks..."  This pattern should be repeated everywhere that you have a fragmentary sentence, e.g. "Number of concurrent threads is..." could be "The number of concurrent threads is...", etc.

**Comment by PRMerger20** [comment]
@AlexGuteniev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@AlexGuteniev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@AlexGuteniev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AlexGuteniev** [comment]
@TylerMSFT, I tried, but may still don't get it right. My native language doesn't have _the_ feature.

**Review by TylerMSFT — CHANGES_REQUESTED** [review]
That's good. Thank you. One final thing: could you update the ms.date of the changed files to reflect that they've been updated. Then I'll sign off. Really appreciate you doing this work.

**Comment by PRMerger17** [comment]
@AlexGuteniev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@AlexGuteniev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@AlexGuteniev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by TylerMSFT — APPROVED** [review]
@AlexGuteniev - thank you very much for your excellent contribution to the Microsoft standard library docs!

**Comment by TylerMSFT** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ktoliver — APPROVED** [review]

**Pull request merged**
