### PR TITLE
Improved abs-class-cpp

### PR DESCRIPTION
**Pull request by jacktherock**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@jacktherock : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by corob-msft** [comment]
@jacktherock 

We appreciate that you've made the effort to contribute a PR. Some are self-explanatory, but this doesn't seem to fit that category. As far as I can tell, you've only changed some styles, and the changes don't fit our style guidelines. What's your intent with this change, or what issue are you trying to address?

**Comment by jacktherock** [comment]
I doesn't have any intent. Just wanted to make some changes to made it more compatible by changing some styles. If you think I did any mistake. You can block my merge otherwise it's in your hand. Thank you!

**Comment by corob-msft** [comment]
@jacktherock Thanks. I'll leave this change out for now.

**Pull request closed without merging**
