### PR TITLE
Remove extra double quote

### PR DESCRIPTION
**Pull request by Rageking8**
Remove a single extra double quote.

### CODE REVIEW

**Comment by Court72** [comment]
@TylerMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — APPROVED** [review]
Thank you. Sorry for the delay. Been out sick.

**Comment by TylerMSFT** [comment]
#sign-off

**Comment by Rageking8** [comment]
> Thank you. Sorry for the delay. Been out sick.

No worries, get well soon.

**Pull request merged**
