### PR TITLE
Change __STDC__ documentation

### PR DESCRIPTION
**Pull request by eldakesh-ms**
In anticipation of commit https://devdiv.visualstudio.com/DevDiv/_git/msvc/pullrequest/372495 preparing the doc changed going along with this.

### CODE REVIEW

**Comment by corob-msft** [comment]
@eldakesh-ms Which version of VS will this fix appear in?

**Comment by eldakesh-ms** [comment]
I anticipate 17.2.

**Comment by PRMerger15** [comment]
@eldakesh-ms : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"

**Comment by corob-msft** [comment]
Closing in favor of MicrosoftDocs/cpp-docs-pr/pull/4043.

**Pull request closed without merging**
