### PR TITLE
[Test Only][Not Merge] public validation

### PR DESCRIPTION
**Pull request by irushx**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@irushx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by fenxu** [comment]
Docs Build status updates of commit _[bf1597a](https://github.com/irushx/cpp-docs/commits/bf1597ab6866765c2a234504c2ebbf6da3fb416c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/index.yml](https://github.com/irushx/cpp-docs/blob/main/docs/index.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/813c26e3-f1ed-5796-cab4-24adc659812f/202206230915571190-4003/BuildReport?accessString=d47e2f041cfd2c0f591ba627365d573493a114a8a20c1f900c3f30e7132b2e6b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/813c26e3-f1ed-5796-cab4-24adc659812f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by PRMerger14** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.

**Comment by PRMerger3** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.

**Comment by jborsecnik** [comment]
@corob-msft, 

Can you review the proposed changes? If you approve, I'd suggest we use "and test" (if that's the meaning), for clarity/translation

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by corob-msft** [comment]
@jborsecnik and other editors:
This change isn't intended to go live. Docs Engineering is using our repo as a testbed for adding PR build validation to the public repo. There's no need to review, edit, or merge this PR. It will be closed at some point.

**Comment by PRMerger7** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.

**Pull request closed without merging**
