### PR TITLE
Add dependency on ninja-build

### PR DESCRIPTION
**Pull request by esweet431**
In VS 2019 16.6 and later Ninja will be the default generator for new Linux/WSL configurations.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@esweet431 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@esweet431 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by corob-msft** [comment]
@esweet431 Erika, does this change have any product version dependencies? 16.6 preview?

**Comment by corob-msft** [comment]
In which case, we should say so, is what I meant to add, before poking the comment button.

**Comment by PRMerger15** [comment]
@esweet431 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by esweet431** [comment]
@corob-msft added version dependency (16.6)

**Pull request merged**
