### PR TITLE
Update C2993

### PR DESCRIPTION
**Pull request by Rageking8**
Removed some old comments that make little sense today and updated the whole page to be valid with the latest info.

### CODE REVIEW

**Comment by Rageking8** [comment]
No rush for review, just wanted to pass the validations and put the PR out there first.

**Comment by Court72** [comment]
@TylerMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — APPROVED** [review]
@rageking8, thank you for improving these examples and particularly for calling out the change in behavior and w/which version.

**Comment by TylerMSFT** [comment]
#sign-off

**Comment by Jak-MS** [comment]
merged

**Pull request merged**
