### PR TITLE
Add xref links

### PR DESCRIPTION
**Pull request by NextTurn**

### CODE REVIEW

**Comment by PRMerger20** [comment]
@NextTurn : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @corob-msft - Could you review the proposed changes? Thanks.

**Comment by Jak-MS** [comment]
@corob-msft  - can you provide specific guidance for this PR. 

- `#sign-off` if it's ready to merge
- `#hold-off` if it requires changes before it's ready for sign off
- `#please-close` - if these changes aren't going to be merged

Thanks!

**Comment by corob-msft** [comment]
@Jak-MS Isn't a review status of "requested changes" sufficiently indicative?

#hold-off

**Comment by Jak-MS** [comment]
@corob-msft - thank you.

**Comment by PRMerger7** [comment]
@NextTurn : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by NextTurn** [comment]
Thanks for clarification.

**Comment by PRMerger15** [comment]
@corob-msft : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Pull request merged**
