### PR TITLE
Repo sync for protected CLA branch

### PR DESCRIPTION
**Pull request by opbld16**
The pull request is created from main637849491143584318 to main to fix git push error for protected CLA branch

### CODE REVIEW

**Comment by PRMerger13** [comment]
@opbld16 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@corob-msft - this has merge conflicts, in case those need to be addressed. thanks.

**Comment by PRMerger8** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by corob-msft** [comment]
@Jak-MS Thanks for the heads-up.

**Pull request merged**
