### PR TITLE
Fix CWnd::FromHandlePermanent description

### PR DESCRIPTION
**Pull request by matrohin**
It was identical to FromHandle one

### CODE REVIEW

**Comment by PRMerger15** [comment]
@matrohin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by TylerMSFT** [comment]
Hi @matrohin, the description is the same because it applies in both cases.

**Comment by TylerMSFT** [comment]
@matrohin, I was in error. You are correct and I will approve this PR. 
Thank you very much for taking the time to improve the docs for everyone.

**Comment by TylerMSFT** [comment]
#sign-off

**Comment by TylerMSFT** [comment]
#please-close

**Pull request merged**
