### PR TITLE
Update os-ot-favor-small-code-favor-fast-code.md

### PR DESCRIPTION
**Pull request by teknixstuff**
Change "minimize or maximize size" to "minimize size or maximize speed"

### CODE REVIEW

**Comment by PRMerger9** [comment]
@teknixstuff : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger14** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by corob-msft — APPROVED** [review]
@teknixstuff Thanks for the update; that was much more confusing than it should have been.

**Pull request merged**
