### PR TITLE
Update documentation for FASTLINK

### PR DESCRIPTION
**Pull request by gregg-miskelly**
The documentation for FASTLINK had a few issues that this PR attempts to address:
* The sentence about "executable is deployed on another computer" was confusing because deploying the executable isn't a problem if you are doing so to remote debug. The real problem is attempting to deploy the PDB.
* The performance notes on FASTLINK were not correct for Visual Studio 2019 and later

### CODE REVIEW

**Comment by gregg-miskelly** [comment]
CC @RussKeldorph

**Comment by jborsecnik** [comment]
@corob-msft, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by corob-msft** [comment]
@gregg-miskelly @RussKeldorph 
The sentence "You can't use this limited PDB to debug on computers other than the computer where the binary and its libs were built, as the PDB isn't intended to be used on any other computer" doesn't seem to imply that it's okay to deploy the binary for test on another computer, as long as the debugging is done remotely from the build computer. Could this be reworded to something like the following?

"You can only use this limited PDB to debug from the computer where the binary and its libraries were built. If you deploy the binary elsewhere, you may debug it remotely from the build computer, but not directly on the test computer."

**Comment by gregg-miskelly** [comment]
Your sentence sounds fine to me. I will update the PR.

**Review by corob-msft — APPROVED** [review]
@gregg-miskelly @RussKeldorph I'm going to approve and merge this, and if you have any updates, we can make that another PR. Thanks for the contribution.

**Comment by RussKeldorph** [comment]
Thanks @gregg-miskelly and @corob-msft for taking care of this!

**Pull request merged**
