### PR TITLE
fix: ordered list

### PR DESCRIPTION
**Pull request by DrAugus**

### CODE REVIEW

**Comment by PRMerger19** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger19** [comment]
@DrAugus : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@TylerMSFT 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by DrAugus** [comment]
this pr seems to be rolled back?

**Comment by Jak-MS** [comment]
Hi @DrAugus - it looks like this got merged as part of a larger sync pr .

**Comment by corob-msft** [comment]
@DrAugus 
Forgive my delay in looking deeper into this issue. At the time, I saw that the [Files changed](https://github.com/MicrosoftDocs/cpp-docs/pull/4055/files) list was empty, so I assumed that your change was mirrored by a change we made locally. Taking a closer look now at the actual commits you made, I see they didn't make it into the docs. Your changes appear to have been overwritten by our automated merge, but I'm not sure how. Not surprisingly, it's not supposed to do that. I apologize for the confusion. 

Your edits look like worthwhile updates, and you deserve credit for making them. If you'd like to submit a new PR with these changes, I'll make sure they appear in the docs:

[docs/parallel/concrt/how-to-use-parallel-invoke-to-write-a-parallel-sort-routine.md](https://github.com/DrAugus/cpp-docs/commit/0503375d03a30b2b4489a7c87aa6057b43b634a5)
[docs/atl/putting-the-control-on-a-web-page-atl-tutorial-part-7.md](https://github.com/DrAugus/cpp-docs/commit/807049dc32550cf0cf8c3507163e162632d2e45b)

Thanks for taking the time to make the docs better, and again, apologies for the poor experience.

**Pull request merged**
