### PR TITLE
Add information about ruleset schema

### PR DESCRIPTION
**Pull request by sunnychatterjee**
This change adds information about the XML schema of rulesets in the existing ruleset documentation.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@sunnychatterjee : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@sunnychatterjee : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by TylerMSFT** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@TylerMSFT: I'm sorry - only the author of this article, @corob-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by corob-msft** [comment]
@TylerMSFT This bounce seems bogus. I wonder what setting controls this?
#sign-off

**Comment by ktoliver** [comment]
Hi @TylerMSFT - PRMerger looks for the value of the `author` metadata attribute as the "authorized" person to approve/sign off on an article that's updated in the public repository. In this repo, that value is set in docs/docfx.json. You can see that @corob-msft is set as the author of articles in this folder:

image


The PR review team can accept another authorized reviewer's approval, aka from ["trusted source"](https://review.docs.microsoft.com/en-us/help/contribute/contribute-vendor-public-prs?branch=master#figuring-out-who-is-a-trusted-source-for-sign-off). You are one, so, we'll merge the PR. We sweep for approved PRs to merge twice a day M-F.

**Pull request merged**
