### PR TITLE
Add more prominent overview links to CX Vector & Map

### PR DESCRIPTION
**Pull request by citelao**
This PR:

* Adds links back to the main Collections (C++/CX) page on `Platform::Collections::Vector` and `Platform::Collections::Map`.
* Adds a note to both classes that they are observable and can be easily bound to XAML properties.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@citelao : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
