### PR TITLE
Split C5000+ warning list

### PR DESCRIPTION
**Pull request by Rageking8**
Summary:
- Split C5000+ warning range into 2 new articles (C5000-C5199 and C5200-C5399).
- This standardizes the range of 200 warnings per article and fix the mismatch where `compiler-warnings-c4800-through-c4999.md` covers range C4800-C5999.

Note 1) One side effect include the new minor mismatch where `compiler-warnings-c4000-c5999.md` now only covers till C5399.

### CODE REVIEW

**Comment by Court72** [comment]
@TylerMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — APPROVED** [review]
Thank you for factoring these out!
There is a bunch of editing going on in this general area by one of the compiler devs. I hope you don't run into a ton of merge conflicts merging this.

**Comment by TylerMSFT** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@TylerMSFT - because this PR contains new articles, we can't merge it here in the public repo. The commits will have to be moved to the private repo and reviewed there (where we have access to better tools). Can you move the commits and open a PR there? Let us know if you'd like assistance. 


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Rastaban** [comment]
> Thank you for factoring these out! There is a bunch of editing going on in this general area by one of the compiler devs. I hope you don't run into a ton of merge conflicts merging this.

I am making my way up from the lower numbered warnings with my edits, so I don't expect to have much conflict up at the 5000+ level. This should make my changes a little easier when I get up there though.

**Comment by TylerMSFT** [comment]
[like]  Tyler Whitney reacted to your message:
________________________________

**Comment by TylerMSFT** [comment]
I'll port the changes to the private repo and submit the PR that way.

**Comment by TylerMSFT** [comment]
Hey @Rageking8 , I ported your work, and did some SEO and description cleanup. [PR #5555](https://github.com/MicrosoftDocs/cpp-docs-pr/pull/5555) just merged, so the work you did here is in and will be live on Monday.
Thanks again for improving the quality of life for C++ doc readers.

**Pull request closed without merging**
