### PR TITLE
Document MSVC doesn't straddle bit-fields

### PR DESCRIPTION
**Pull request by workingjubilee**
This PR documents existing behavior in the MSVC toolset.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@workingjubilee : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger13** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by corob-msft — APPROVED** [review]
@workingjubilee 
Thanks for the contribution. We mention this implementation-specific behavior in a very oblique way in [Padding and alignment of structure members](https://docs.microsoft.com/en-us/cpp/c-language/padding-and-alignment-of-structure-members?view=msvc-160), and in the Bitfields section of [x64 software conventions](https://docs.microsoft.com/en-us/cpp/build/x64-software-conventions?view=msvc-160#bitfields) (though the compiler behavior isn't x64-specific). Those pages aren't necessarily where people would go to find this out, so this seems a good place to add that info. I've modified your content to follow our voice and internationalization guidelines.

**Comment by workingjubilee** [comment]
Ah, I missed that. Thank you, cross-referencing it does seem appropriate.

**Pull request merged**
