### PR TITLE
Update how-to-convert-between-various-string-types.md

### PR DESCRIPTION
**Pull request by drvoss**
LPCTSTR can be converted LPCWSTR. But it depends on the condition. UNICODE or not. So, LPCWSTR is better.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@drvoss : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by GitHubber17** [comment]
@corob-msft - Would you review the proposed changes? Thanks

**Comment by PRMerger16** [comment]
@corob-msft : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by corob-msft** [comment]
Closing this pending a rewrite at some point in the future.

**Pull request closed without merging**
