### PR TITLE
MASM: Fix broken links in processor manufacturers page

### PR DESCRIPTION
**Pull request by nir9**
Also remove the introduction to AVX link which no longer works and I couldn't find this article on Intel's website, AVX is explained anyway in the SDM so I think it should be fine to remove that.

### CODE REVIEW

**Comment by ttorble** [comment]
@TylerMSFT 

Can you review the proposed changes?  

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge.  

#label:"aq-pr-triaged" 
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — APPROVED** [review]
thank you for fixing the links

**Comment by TylerMSFT** [comment]
#sign-off

**Comment by TylerMSFT** [comment]
#hold-off

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
