### PR TITLE
Augment C2082

### PR DESCRIPTION
**Pull request by Rageking8**
Modify parameter and local variable names to align comments. Add a lambda example to the mix.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@TylerMSFT 
- Can you review this PR? (assuming the validation and build pass this time)
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — APPROVED** [review]
Nice touch with the lambda example :-)

**Comment by TylerMSFT** [comment]
#sign-off

**Comment by ShannonLeavitt** [comment]
Thanks @Rageking8

**Pull request merged**
