### PR TITLE
Document new rule C26820

### PR DESCRIPTION
**Pull request by dmitrykobets**
Existing PR: https://devdiv.visualstudio.com/DevDiv/_git/msvc/pullrequest/237948

### CODE REVIEW

**Comment by PRMerger7** [comment]
@dmitrykobets : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @corob-msft - Could you work with @dmitrykobets to move this commit to the private repo and ensure that it meets all [PR review quality criteria](https://review.docs.microsoft.com/help/contribute/contribute-how-to-write-pull-request-quality-criteria?branch=master)? It should pass build validation, be added to a TOC, be viewed on staging, and be PR-reviewed before being merged in the private repo. Thanks.

**Comment by PRMerger14** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by corob-msft** [comment]
... and I'll move it to the private repo. I missed Kristine's comment before starting my edits.

**Comment by corob-msft** [comment]
Closing in favor of the private repo version [Document new rule C26820](https://github.com/MicrosoftDocs/cpp-docs-pr/pull/2798) #2798.

**Pull request closed without merging**
