### PR TITLE
largeaddressaware:no is not recommended for 64-bit apps

### PR DESCRIPTION
**Pull request by mspll**

### CODE REVIEW

**Comment by Jak-MS** [comment]
@TylerMSFT 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — CHANGES_REQUESTED** [review]
Hi @mspll,
Thank you for taking the time to contribute to the docs!
I'd like to take this contribution but would like to tone down the 'result in runtime failures' part. The way it is written implies that using the switch can generate runtime failures. As you know, the problem is that memory usage is limited to 2gb, and if your program fills it up (which most don't come close to) then you could potentially hit a runtime error. But I don't want to imply that the switch results in runtime failures. Can you update?

**Comment by mspll** [comment]
@TylerMSFT One case where this causes runtime failures is trying to run a non-large-address-aware x64 EXE on an ARM64 system. The emulation runtime tries to reserve a 4 GB region of VA space and fails, so the process doesn't even start.

**Comment by GitTyler** [comment]
That's an interesting scenario. What do you think about something like this, then:

Linking 64-bit applications with **`/LARGEADDRESSAWARE:NO`** is not recommended. It restricts the amount of available address space available to your app which can result in runtime failures if the app exhausts memory. It may also prevent x64 apps from running on ARM64 systems because the emulation runtime will try to reserve 4GB of virtual address space. If the app was linked with `/LARGEADRESSAWARE:NO`, the app won't launch because allocating that much address space will fail.

Awesome of you to update this page as a result of your experience!

**Review by TylerMSFT — APPROVED** [review]

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
