### PR TITLE
Fix unclosed links

### PR DESCRIPTION
**Pull request by HarryGwinnell**
Fix unclosed link tags causing the whole page to appear as a link.

e.g. After Filename Macros in Special NMAKE macros, the unclosed link makes the paragraph text appear as a link

image

### CODE REVIEW

**Comment by Court72** [comment]
@TylerMSFT

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — APPROVED** [review]
Wow - thank you for fixing that.

**Comment by TylerMSFT** [comment]
#sign-off

**Comment by ShannonLeavitt** [comment]
@TylerMSFT - I see one minor inconsistency in the final correction in the diff view. Is this okay, or should the forward slash be removed in line 266?

image

**Comment by TylerMSFT** [comment]
Sharp eye. I fixed that one.

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
