### PR TITLE
Update multithreading-and-locales.md

### PR DESCRIPTION
**Pull request by Antonz0**
Wrong `setlocale()` reference, it should be a C runtime function, not a preprocessor macro.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@Antonz0 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@TylerMSFT 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by corob-msft — APPROVED** [review]
At least we were consistent. This change looks good to me. Thanks, @Antonz0

**Comment by corob-msft** [comment]
#sign-off

**Comment by PRMerger18** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @tylermsft

**Pull request merged**
