### PR TITLE
correction at line 137,139

### PR DESCRIPTION
**Pull request by MUzairS15**
"VT_DISPATCH"--->IDISPATCH*
"VT_UNKNOWN"--->IUNKNOWN*

### CODE REVIEW

**Comment by PRMerger13** [comment]
@MUzairS15 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MUzairS15** [comment]
Pls tell if anything wrong

**Comment by PRMerger15** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by corob-msft — APPROVED** [review]
@MUzairS15 Looks fine, thanks for the update.

**Pull request merged**
