### PR TITLE
Update wcstombs-s-wcstombs-s-l.md

### PR DESCRIPTION
**Pull request by mohammad-ghasemi-2549**
count parameter should reserve one place for the terminating null character.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@mohammad-ghasemi-2549 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by TylerMSFT — CHANGES_REQUESTED** [review]
@mohammad-ghasemi-2549 , thank you for your interest in the docs. I'm not sure your change is correct. The docs call out that the `count` parameter specifically *does not* account for the NULL character.

**Comment by mohammad-ghasemi-2549** [comment]
exactly

**Review by TylerMSFT — APPROVED** [review]

**Comment by TylerMSFT** [comment]
#sign-off
We are running into this problem again where the contributor license agreement appears to have been signed but the status is still pending.

**Comment by TylerMSFT** [comment]
@mohammad-ghasemi-2549, could you try signing the CLA again above? I'd like to get your change merged.

**Comment by PRMerger16** [comment]
@TylerMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
The CLA signing problem appears to be resolved. Merging now.

**Pull request merged**
