### PR TITLE
Document that `__fastfail` is `noreturn`

### PR DESCRIPTION
**Pull request by MisterDA**

### CODE REVIEW

**Comment by Court72** [comment]
@TylerMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by MisterDA** [comment]
Note that if I'm not mistaken, there's a bug with the C compiler (not C++ !), which seems to ignore the  noreturn annotation during unreachable code analysis. 
https://developercommunity.visualstudio.com/t/C-Code-Analysis-should-understand-that/10665570

**Review by TylerMSFT — APPROVED** [review]
Thank you.

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
