### PR TITLE
Update casting-c-cx.md

### PR DESCRIPTION
**Pull request by Jaiganeshkumaran**

### CODE REVIEW

**Comment by PRMerger5** [comment]
@Jaiganeshkumaran : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@Jaiganeshkumaran : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by corob-msft — APPROVED** [review]
@Jaiganeshkumaran Looks good, thanks for making these updates.

**Pull request merged**
