### PR TITLE
Update basic-string-class.md

### PR DESCRIPTION
**Pull request by mohammad-ghasemi-2549**
In the overload that the count parameter can be specified, you can have a nullptr as ptr if count == 0;

### CODE REVIEW

**Comment by PRMerger14** [comment]
@mohammad-ghasemi-2549 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@TylerMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by TylerMSFT — APPROVED** [review]
Thank you, @mohammad-ghasemi-2549 Really appreciate you helping improve the docs. I made a small change per our code style guidelines. This is approved.

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
