### PR TITLE
[sanitizers] Add documentation for custom allocators

### PR DESCRIPTION
**Pull request by strega-nil-ms**
As part of microsoft/stl#3164, add documentation for `_Minimum_asan_allocation_alignment`

### CODE REVIEW

**Comment by corob-msft** [comment]
@strega-nil-ms Hi, Nicole - I gave the content an edit pass so it doesn't trigger validation problems in the grammar checker. If you'd be so kind as to give it a closer look to make sure I didn't change the meaning of the content, I'd appreciate it. Feel free to clarify anything I may have muddied up in the process.

**Review by corob-msft — APPROVED** [review]

**Comment by Court72** [comment]
@corob-msft 

Thanks for the review! 
When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by corob-msft** [comment]
@strega-nil-ms 
One more question: Does this reflect the current state of the product, and if so, as of which release?

**Comment by strega-nil-ms** [comment]
@corob-msft mmh, it should probably be kept until 17.6, since the `_Minimum_asan_allocation_alignment` variable is not yet implemented.

**Comment by strega-nil-ms** [comment]
@corob-msft is there a good way to say "this section only applies after 17.6 preview 1" or something along those lines?

**Comment by corob-msft** [comment]
@strega-nil-ms 
That's fine. We use a standard convention for noting minor version features, like "This feature is available in Visual Studio 2022 version 17.6 preview 1 and later".
I've been meaning to figure out how to move this PR to the private repo, since it's likely to hang out here unmerged for a few more weeks until the 17.6 previews become public. In the private repo you can preview it with more fidelity, and we can tag it with the release it's supposed to be merged into. Unfortunately, my git-fu is weak when it comes to cross-repo moving of commits.

**Comment by strega-nil-ms** [comment]
@corob-msft I can certainly do that if you could send me how to access it on teams (nimazzuc).

**Comment by strega-nil-ms** [comment]
@corob-msft done! gonna close this one.

**Pull request closed without merging**
