### PR TITLE
Missing characters in /docs/c-language/lexical-grammar.md

### PR DESCRIPTION
**Pull request by Johnsonsky**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@Johnsonsky : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@Johnsonsky : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by corob-msft — APPROVED** [review]
@Johnsonsky 
Looks good, thanks for the updates.

**Pull request merged**
