### PR TITLE
`/hotpatch`: No jump to the first instruction

### PR DESCRIPTION
**Pull request by AlexGuteniev**

### CODE REVIEW

**Comment by PRMerger10** [comment]
@AlexGuteniev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger5** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by corob-msft — APPROVED** [review]
Thanks for the addition, @AlexGuteniev. I give the grammar a slight tweak to make our automatic checker happy.

**Pull request merged**
