### PR TITLE
Document /arch:AVX512 command-line option

### PR DESCRIPTION
**Pull request by jpmorgan-atMS**
This change documents the effect of the /arch:AVX512 command-line option. Some differences between the x86 and x64 pages describing the /arch: option were resolved. The predefined identifier page was also updated to reflect the macros defined specifically for AVX-512. The macros added signify the specific AVX-512 subsets that can be used for code generation under /arch:AVX512.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@jpmorgan-atMS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
