### PR TITLE
Improve errno Constants page

### PR DESCRIPTION
**Pull request by ccawley2011**
The table has been combined with the one from the `errno`, `_doserrno`, `_sys_errlist`, and `_sys_nerr` page, and the values for the POSIX error codes have been added.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@ccawley2011 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by TylerMSFT** [comment]
Hi @ccawley2011, thank you for taking time to improve the docs. I'll review this but am in the middle of getting ready for a release. I will come back to this, but it will be a bit.  Didn't want you to think this is forgotten.

**Comment by corob-msft** [comment]
@ccawley2011 @TylerMSFT 
This looks like a fine addition. There are a couple of style issues I'd fix. I'd recommend using alphabetical order on the constant names, rather than ordering them by their values, for ease of lookup. I'd also recommend switching to `code` style for the constants, for `errno` itself, flags like `_O_CREAT`, and for function names, such as `_open`. Also, tables are easier to read if they have spaces between the pipe characters and cell contents, and it looks like the last pipe character in `_STRUNCATE` in the first table is missing. It doesn't affect rendering, but it's a good style practice, especially if you're going to sort rows.

**Comment by PRMerger17** [comment]
@ccawley2011 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by corob-msft — APPROVED** [review]
@ccawley2011 It's taken a long time to get back to this. I've fixed some style issues and made other fixes to make our build system happy. Thanks for your contribution, we appreciate it.

**Pull request merged**
