### PR TITLE
Add examples for void type in cpp (#4331)

### LINKED ISSUE #4331: More explicit example for void keyword.
The example provided on this page could be more explicit.
More precisely, the example provided does not cover two cases it could easily provide.

``int main()`` could become ``int main(void)``

also a function declaration returning void could be added such as

void print_num(int num)
{
    std::cout << num << std::endl;
}

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06924698-5d51-7597-3aa0-80738e561248
* Version Independent ID: 45016f75-582b-d9b2-0bdd-16854c1ddb3a
* Content: [void (C++)](https://learn.microsoft.com/en-us/cpp/cpp/void-cpp?view=msvc-170)
* Content Source: [docs/cpp/void-cpp.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/void-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

### PR DESCRIPTION
**Pull request by AdrianWeaver**
Adding examples to cpp void page to comply with the description made in the above text.
Also fixing bracket to comply with code norm given as example in guidelines.
Fixes #4331

### CODE REVIEW

**Comment by Court72** [comment]
@corob-msft 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by corob-msft — APPROVED** [review]
@AdrianWeaver Thanks for the update and proposed fix for #4331. I've expanded on it with some extra info. It should be published by tomorrow sometime.

**Review by corob-msft — APPROVED** [review]

**Comment by corob-msft** [comment]
@AdrianWeaver 
I apologize, I edited your contribution too much, which pushed it over the license threshold. We'd like to give you credit for the update, but now it requires you to sign the CLA. If you do, I'll merge the change. Thanks!

**Comment by AdrianWeaver** [comment]
Hello,
Thank you for keeping me in the loop.

There is absolutely no worries for me. I will have a look at the CLA
tomorrow to sign it.

I am not affiliated with any company and will therefore sign it on my own.

Sincerely yours,
Adrian Weaver


Le lun. 12 déc. 2022 à 22:15, Colin Robertson ***@***.***> a
écrit :

**Comment by AdrianWeaver** [comment]
@microsoft-github-policy-service agree

**Review by corob-msft — APPROVED** [review]
@AdrianWeaver Thanks for the contribution, and your patience.

**Pull request merged**
