### PR TITLE
Fix incorrect import example

### PR DESCRIPTION
**Pull request by roxk**

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@roxk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"

**Comment by corob-msft** [comment]
Related issue: #3558

**Review by corob-msft — APPROVED** [review]
@roxk Thanks for taking the time to submit a fix. We appreciate it.

**Pull request merged**
