### PR TITLE
Give linux media standardized filenames

### PR DESCRIPTION
**Pull request by corob-msft**
Change names in PR #1673 to match doc styleguide standards.

### CODE REVIEW

**Comment by corob-msft** [comment]
@mikeblome Mind giving this an approval?
If we change the filenames here before the others are merged into the private repo, it saves some grief.

**Comment by corob-msft** [comment]
@esweet431 FYI in case you're writing content to use these filenames.

**Comment by Jak-MS** [comment]
@corob-msft - changing file names in the public repo can be tricky because we don't have validation tools to check affected docs that link to the files. and if the files are already in master they'll need redirects associated, which we can't test here. (recommend moving this to the private repo).

**Comment by mikeblome** [comment]
@jak-MS these are new files with no current links in the repo

**Comment by Jak-MS** [comment]
@mikeblome @corob-msft - ignore my comment about redirects... i see these are image files.

**Pull request merged**
