### PR TITLE
Merge code blocks for C2504

### PR DESCRIPTION
**Pull request by Rageking8**
Merge both code blocks together as the second one does not have proper syntax highlighting and its slighter more terse this way. Also did some light formatting for the example and text.

### CODE REVIEW

**Comment by Court72** [comment]
@TylerMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by TylerMSFT** [comment]
@rageking8, thank you for helping out with the docs.
This week I'm working to a deadline for some other content, so it'll be a week or so before I can look at these. Take care.

**Review by TylerMSFT — APPROVED** [review]
That's an improvement. Thank you.

**Comment by TylerMSFT** [comment]
#sign-off

**Comment by ShannonLeavitt** [comment]
Thanks @rageking8

**Pull request merged**
