### PR TITLE
buil: Add MarkdownLint GitHub Action

### PR DESCRIPTION
**Pull request by nschonni**
This is the same setup from the dotnet/docs repo, which a slight change to ignore the TOC.md files.

### CODE REVIEW

**Comment by nschonni** [comment]
https://github.com/MicrosoftDocs/cpp-docs/pull/1996 should probably land first, since otherwise the build will be red

**Comment by ktoliver** [comment]
@corob-msft Do you know what you'd like to do with this PR? Thanks.

**Comment by corob-msft** [comment]
@nschonni , @ktoliver 
The reason I'm sitting on this PR is because it's in conflict with some experimental workflows we're using internally. That's why the workflows folder is currently listed in the .gitignore file. It lets us experiment with workflows independently of what gets picked up for shipping. This PR strips that protection and might let out workflows in progress that aren't ready for prime time. However, the workflow in this PR is also quite useful and something we want to provide to contributors in some form. So, no action just yet. But definitely a thumbs up and it's on the radar.

**Comment by nschonni** [comment]
@corob-msft I've updated the .gitignore so that other workflows are ignored, but this one will be included.
Alternately, I could just force add the file and not touch the gitignore, but then any further changes will need to be manually force added as well

**Comment by ktoliver** [comment]
@corob-msft Something in PRMerger automation is causing this PR to appear as updated several times a day (although no change shows in the UI or conversation history). It seems to be associated with a label that's applied automatically; we are troubleshooting. Meanwhile, PR reviewers have to wade through a handful of PRs that are in the same unchanged but "updated" state as we process recently updated PRs throughout the day. I'm going to try adding hold-off and see if that stops the continual updating and floating the PR to the top as recently updated. It might not work, but that's the reason for this #hold-off. If it works, I will hold off on PR https://github.com/MicrosoftDocs/cpp-docs/pull/1996 also. Thanks!

**Comment by corob-msft** [comment]
@ktoliver Good to know, thanks!

**Comment by ktoliver** [comment]
@corob-msft There's a technical issue in PRMerger in which this PR continually floats to the top of the PR reviewer's to-do queue. Assigning different labels and hold-off have had no effect. Because this PR might be open for an indefinite length of time, would it be OK with you if we close it, and you can reopen it when you are ready to take action on the proposed updates? Please advise. Thanks.

**Comment by corob-msft** [comment]
Closing temporarily for reviewer assistance.

**Comment by ktoliver** [comment]
Thank you @corob-msft

**Pull request closed without merging**
