### PR TITLE
Clarify terminology around register volatility.

### PR DESCRIPTION
**Pull request by pmsjt**
Volatile vs Non-volatile is a very Microsoft specific terminology. Out in the industry, register calling convention assignment are more frequently referred to as Caller vs Callee saved.

Also, x18 is a reserved register, so it is neither Caller nor Callee Saved.

### CODE REVIEW

**Comment by Court72** [comment]
@TylerMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — CHANGES_REQUESTED** [review]
Hi @pmsjt, it was cool of you to update this page. I'm unfortunately not going to take this PR because although I think you are right that caller-saved and callee-saved are more widely used outside of MS, these changes then make this one doc inconsistent with our other docs. For better or for worse, MS went down the road of this terminology and I'd want to make a MS-wide change to our documentation rather than become inconsistent with ourselves. It's not a wonderful situation but I unfortunately don't have the time to undertake such an effort.

**Comment by pmsjt** [comment]
@TylerMSFT please reopen the PR so I can address the feedback. I don't have the permissions to do so. If you Close the PR I can't address the comments.

**Comment by pmsjt** [comment]
Thank you for the feedback @TylerMSFT. I agree it is best to keep terminology consistent. I revised the change to touch only the cases where taxonomy was objectively incorrect and aimed to clarify the usage without introducing new terminology.

Please let me know if this is more palatable.

**Review by TylerMSFT — APPROVED** [review]
Thank you very much!

**Comment by Court72** [comment]
@TylerMSFT

Thanks for reviewing the proposed changes.

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge.

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
