### PR TITLE
Update linker-tools-error-lnk1107.md as the description couldn't help me on resolving the linker error and could get the solution from stackoverflow

### PR DESCRIPTION
**Pull request by chaitanyavaleti**

### CODE REVIEW

**Comment by PRMerger4** [comment]
@chaitanyavaleti : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by corob-msft** [comment]
@chaitanyavaleti 
Thanks for taking the time to make an update. While you're not wrong, neither is the existing suggestion, which matches the example. What LNK1107 really means is, the linker tried to link something that's not one of the expected input types (or if it is an expected input type, the file is corrupted.) The expected input file types are usually .obj or .lib files, or a compiled resource or manifest, Common unexpected files that cause this error are .dll files or source files. Sometimes the unexpected files appear on the linker command line because something is broken in the build process, so the options sent to link.exe are incorrect. 

I'm not sure what to do with your update. It doesn't have enough context to provide a good solution (but to be fair, neither does the existing content.) Perhaps it's better to [restate the problem as an issue](https://github.com/MicrosoftDocs/cpp-docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%20389e3ae9-b2c7-652d-aa64-041b458babdd%0A*%20Version%20Independent%20ID%3A%20d69f5bdf-b17b-2b62-089d-ea3adcc17b82%0A*%20Content%3A%20%5BLinker%20Tools%20Error%20LNK1107%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fcpp%2Ferror-messages%2Ftool-errors%2Flinker-tools-error-lnk1107%3Fview%3Dmsvc-170)%0A*%20Content%20Source%3A%20%5Bdocs%2Ferror-messages%2Ftool-errors%2Flinker-tools-error-lnk1107.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoft%2Fcpp-docs%2Fblob%2Fmaster%2Fdocs%2Ferror-messages%2Ftool-errors%2Flinker-tools-error-lnk1107.md)%0A*%20Product%3A%20**visual-cpp**%0A*%20Technology%3A%20**cpp-diagnostics**%0A*%20GitHub%20Login%3A%20%40corob-msft%0A*%20Microsoft%20Alias%3A%20**corob**) first, then we can determine the best solution.

**Comment by corob-msft** [comment]
Closed, since this is covered by another update that should be visible on Monday.

**Pull request closed without merging**
