### PR TITLE
Add section on CMake partial activation

### PR DESCRIPTION
**Pull request by sfreed141**
This describes a new feature being added in 17.1 preview 2, so this documentation should be published around the same time that preview becomes available (I think 12/14).

### CODE REVIEW

**Comment by PRMerger9** [comment]
@sfreed141 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"

**Comment by corob-msft** [comment]
Thanks, @sfreed141 !

In the future, if you want to embargo content until release, I recommend [making your PR in the cpp-docs-pr repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-options?branch=master) instead. But no need to bother with this one, I'll watch the release schedule and merge when the bits drop, give or take. 

Are you the best contact for other CMake-related issues as they come up? My usual go-to, @esweet431, just announced her departure for another team. I'm on the lookout for another subject-matter expert.

**Comment by sfreed141** [comment]
> Thanks, @sfreed141 !
> 
> In the future, if you want to embargo content until release, I recommend [making your PR in the cpp-docs-pr repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-options?branch=master) instead. But no need to bother with this one, I'll watch the release schedule and merge when the bits drop, give or take.
> 
> Are you the best contact for other CMake-related issues as they come up? My usual go-to, @esweet431, just announced her departure for another team. I'm on the lookout for another subject-matter expert.

Thanks for the info, I'll use the other repo next time. As for the contact my lead @bobbrow is probably the best person to go to.

**Comment by PRMerger10** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by corob-msft — APPROVED** [review]
Merging for publication by release of Preview 2.

**Pull request merged**
