### PR TITLE
Added example program outputs (#3892)

### LINKED ISSUE #3892: `<algorithm>` doc file missing example implementation output + problem with `equal_range` example
Doc file [algorithm-functions.md](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/standard-library/algorithm-functions.md) is missing output of example code in numerous locations. 

The code example for `equal_range` has compile errors when compiling with `c++17`.

ISO paper for this feature: [PaperID]()
First implemented in: VS YYYY major.minor

### PR DESCRIPTION
**Pull request by BrandonPacewic**
This pr fixes #3892.

Added program output for example code as well as fixed the compile errors within the `equal_range` example code.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@BrandonPacewic : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by BrandonPacewic** [comment]
After looking through more of the documentation it has occurred to me that lots of example code sections do not contain the output of said code. Is this on purpose or because of how each individual decided to write each doc section?

**Review by TylerMSFT — APPROVED** [review]
Thank you for adding the output examples and improving the docs.

**Comment by TylerMSFT** [comment]
@BrandonPacewic, regarding your question about output samples, yes, it can vary by writer. Some of these docs are very old, were authored at different times when cpub standards and emphasis were different, or came from an earlier publishing system and may have suffered at the hands of automated conversion to the new format. Or someone may have decided that including the output wouldn't add any descriptive value because it was self-evident. Regardless of the reasons, thank you for adding value here. Much appreciated.

**Comment by BrandonPacewic** [comment]
Absolutely, looking forward to making more contributions when I can.

**Comment by BrandonPacewic** [comment]
@TylerMSFT Just noticed that you never signed off. Was there something else required of me that I need to do?

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
