### PR TITLE
Update %Z specifier with known issue

### PR DESCRIPTION
**Pull request by amyw-msft**
There is a known issue in the Universal C Runtime %Z specifier that it is unlikely we will be able to change for application compatibility (the issue has existed since 2015).  Instead of %Z -> ANSI_STRING and %wZ -> UNICODE_STRING, the specifier acts like the %S specifier and expects the "opposite" type of string from the API used.

### CODE REVIEW

**Comment by chopperchyk** [comment]
Kimberly Terlap,Otis Chaunceyjr hacked my phone,emails,they have my drivers
license,birth certificate,social security card,consealed weapons permit,all
my credit cards,fir the past 4 years and have been using it,they are
subscribed to this and all threads relating to gifthub,using this yo hack
Mt phone, I have changed phones ,phone numbers,emails,to no email. Police
no help,if you can suggest anything yo make it stop,please help me.

**Comment by Jak-MS** [comment]
@TylerMSFT 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — APPROVED** [review]
#sign-off

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
