### PR TITLE
Remove extraneous empty lines

### PR DESCRIPTION
**Pull request by Rageking8**

### CODE REVIEW

**Comment by Jak-MS** [comment]
@TylerMSFT 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — APPROVED** [review]
Thanks for the cleanup :-)

**Comment by TylerMSFT** [comment]
#sign-off

**Comment by ShannonLeavitt** [comment]
Thanks @Rageking8

**Pull request merged**
