### PR TITLE
Repo sync for protected CLA branch

### PR DESCRIPTION
**Pull request by opbld16**
The pull request is created from master637636092850540086 to master to fix git push error for protected CLA branch

### CODE REVIEW

**Comment by PRMerger17** [comment]
@opbld16 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
See comments in https://github.com/MicrosoftDocs/visualstudio-docs/pull/6906#issuecomment-892071813

**Comment by ShannonLeavitt** [comment]
See https://github.com/MicrosoftDocs/visualstudio-docs/pull/6906#issuecomment-892071813 for comments that relate do this.

**Review by corob-msft — APPROVED** [review]

**Comment by corob-msft** [comment]
@ShannonLeavitt 
I don't think the issue in the visualstudio-docs-pr repo applies here. We don't have automation that automatically merges updates from cpp-docs-pr into cpp-docs. We've always merged these by hand. The automation going the other way also requires manual intervention. We rarely get more than one submission to the public repo in a day, so I don't think we've had issues with squashing the auto-generated PRs yet. The other issue about PRs that qualify for auto merge not being auto merged hasn't been tested yet, so we might have the same problem Gordon describes.

**Pull request merged**
