### PR TITLE
Update Linux IntelliSense behavior

### PR DESCRIPTION
**Pull request by esweet431**
Update Linux IntelliSense behavior with brief description and link to more detailed blog post.
I did this in a note since the behavior only applies to 16.5+ - but please let me know if there is a better way to communicate this information.

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @mikeblome - Could you review the proposed changes to the article? Thanks.

**Comment by esweet431** [comment]
CC @corob-msft

**Comment by corob-msft** [comment]
@ktoliver Hi, Kristine - Mike Blome has retired as of 12/31. For now, it's just me doing the cpp-docs repo administration. Is there a way to let the Aquent editors know?

**Comment by ktoliver** [comment]
> @ktoliver Kristine Toliver (Aquent LLC) Vendor Hi, Kristine - Mike Blome has retired as of 12/31. For now, it's just me doing the cpp-docs repo administration. Is there a way to let the Aquent editors know?

Hi @corob-msft Oh, that's excellent for him. I will send email to the Aquent team to let them know. Thanks for sharing the info.

**Pull request merged**
