### PR TITLE
crtsetdbgflag.md: _CrtCheckMemory is not called by default

### PR DESCRIPTION
**Pull request by oold**

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@oold : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@TylerMSFT 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by TylerMSFT** [comment]
Thanks, @oold. Let me check into this a little bit and then I'll circle back to this change.

**Review by TylerMSFT — APPROVED** [review]
Thank you, @oold. Incorporating your change.

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
