### PR TITLE
fix: MD033/no-inline-html

### PR DESCRIPTION
**Pull request by nschonni**
Escape elements swallowed as HTML

### CODE REVIEW

**Comment by PRMerger9** [comment]
@nschonni : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
