### PR TITLE
Update _MSC_VER table with VS2022 RTW version.

### PR DESCRIPTION
**Pull request by danieljennings**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@danieljennings : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by corob-msft — APPROVED** [review]
@danieljennings Thanks for the update. I've got a PR in the works that includes this, but I can fix any merge issues later.

**Comment by danieljennings** [comment]
Thank you, @corob-msft . When I was looking for the value online I found it missing here and on the Wikipedia page that (apparently) lists all of the _MSC_VER options, so I figured I'd update both of them for future travelers.

**Pull request merged**
