### PR TITLE
Adds missing ml64 /quiet flag documentation

### PR DESCRIPTION
**Pull request by MattBolitho**
The current `ml64` command-line reference seems to be missing documentation for the `/quiet` flag. This flag seems to have been added about a year ago as a result of [this CMake issue](https://gitlab.kitware.com/cmake/cmake/-/issues/23537). I couldn't find much more about it online.

Running `ml64 /?` with version `14.41.34120.0` prints the following information: `/quiet Suppress 'Assembling' message`. This PR adds that text but conjugated like the other option descriptions in the table.

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@TylerMSFT

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by MattBolitho** [comment]
@TylerMSFT is there anything specific needed for this one?

**Review by TylerMSFT — APPROVED** [review]
Thank you for adding this.

**Comment by TylerMSFT** [comment]
@MattBolitho , what version of VS does this become available in? We should note that if it is a new flag.

**Comment by MattBolitho** [comment]
> @MattBolitho , what version of VS does this become available in? We should note that if it is a new flag.

It is available from `17.6`. I will add that to the table entry when I get a chance!

**Comment by TylerMSFT** [comment]
Thanks, @MattBolitho. Sending this through.
#sign-off

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
