### PR TITLE
Clarified which New Project should be selected (for VS 2022)

### PR DESCRIPTION
**Pull request by enricosebastian**
There are two options; one does not work (.NET) due to the prerequisites set in the guide.

### CODE REVIEW

**Comment by Court72** [comment]
@TylerMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by TylerMSFT** [comment]
Thanks, @enricosebastian.  I think the problem is deeper in this topic because it doesn't discuss at all the difference between creating a project for .NET Framework (the original Windows-only version of .NET) or what was once known as .NET Core (the .NET option). You mentioned the pre-requisites pushing you to needing the windows version. I don't see that in the prereqs, though if you do try the suggested example then it needs to be the windows version (.NET Framework).  Can you tell me a little more about what in the prereqs suggested to you that it needed to be the Windows version of the .NET framework?  I agree a change needs to be made here, I think it may be more than just picking a different template.

**Comment by enricosebastian** [comment]
> Thanks, @enricosebastian. I think the problem is deeper in this topic because it doesn't discuss at all the difference between creating a project for .NET Framework (the original Windows-only version of .NET) or what was once known as .NET Core (the .NET option). You mentioned the pre-requisites pushing you to needing the windows version. I don't see that in the prereqs, though if you do try the suggested example then it needs to be the windows version (.NET Framework). Can you tell me a little more about what in the prereqs suggested to you that it needed to be the Windows version of the .NET framework? I agree a change needs to be made here, I think it may be more than just picking a different template.

Hi @TylerMSFT! Been following the C++/CLI documentation for a few days now because I will be needing it for a project at work. Followed the guide, but found out that there would be two CLR Empty Projects options; one that's .NET and another that's .NET Framework. It didn't specify nor differentiate between the two in the walkthrough (or perhaps I missed that par. Sorry, rushing my project hahaha).

Decided to try both .NET and .NET Framework; the former would result in `...\...\...\x64\Debug\[name].dll is not a valid Win32 application`, but the .NET Framework would work with no hiccups (and is the method I am currently using for work). Did not decide to look further into the issue yet, but I did follow the setup prereqs via VS Installer.

I do agree with you that a total rework might be needed (or at least the section is split to differentiate between the two C++/CLI projects), but right now this edit will be a big help for those like me just starting to read through the documentation, and just need to see the output

**Review by TylerMSFT — APPROVED** [review]
Thanks, @enricosebastian!

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
