### PR TITLE
Endlicher Motor

### PR DESCRIPTION
**Pull request by kursfunkschirm**
https

[placeholder.txt](https://github.com/MicrosoftDocs/cpp-docs/files/4272230/placeholder.txt)
img16
img15

[placeholder.txt](https://github.com/MicrosoftDocs/cpp-docs/files/4272245/placeholder.txt)
[dropbox.pdf](https://github.com/MicrosoftDocs/cpp-docs/files/4272252/dropbox.pdf)
[vscodevim.vim-unresponsive.cpuprofile.txt](https://github.com/MicrosoftDocs/cpp-docs/files/4272255/vscodevim.vim-unresponsive.cpuprofile.txt)

://github.com/kursfunkschirm

### CODE REVIEW

**Comment by PRMerger10** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by corob-msft** [comment]
This is unexpected. Please don't touch it until after the automation has run this morning for the live update, and discussing it with me.

**Comment by ktoliver** [comment]
The PR is pulling in changes made in other PRs and repos. And no CLA has been signed. I think it should be closed.

@tfosmark

**Comment by ktoliver** [comment]
It looks like it auto-merged?

**Comment by corob-msft** [comment]
I don't understand what happened here. I'm opening an issue.

**Comment by corob-msft** [comment]
Opened [183056](https://ceapex.visualstudio.com/CPS/_workitems/edit/183056).

**Pull request merged**
