### PR TITLE
Add description for new warning C26826

### PR DESCRIPTION
**Pull request by dmitrykobets-msft**

### CODE REVIEW

**Comment by corob-msft** [comment]
@dmitrykobets-msft 
Thanks, Dmitry. Does this warning appear starting in a particular version of VS? That is, is it in VS 2019 version 16.11 (or earlier), or does it require VS 2022?

**Comment by dmitrykobets-msft** [comment]
@corob-msft The warning is implemented in 17.1 Preview 1, and the VS-side of the changes were merged into main on October 12.

**Comment by PRMerger12** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by corob-msft — APPROVED** [review]
@dmitrykobets-msft 
Thanks for the update - sorry about the delay.

**Pull request merged**
