### PR TITLE
Update cpen-class.md

### PR DESCRIPTION
**Pull request by BigB9898**
0 pen width description is not clear.  Updating this document along with several others.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@BigB9898 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by TylerMSFT — CHANGES_REQUESTED** [review]
Thank you, @BigB9898 . How you've rephrased this is better than the original, but I'm worried that we lost the specifics of the device units being 1 pixel. Could you strengthen that part? 
Super minor: the diff looks like there are now two periods at the end. That may be weirdness in how the diff is presented, but something to take a quick look at.

**Comment by BigB9898** [comment]
> Thank you, @BigB9898 . How you've rephrased this is better than the original, but I'm worried that we lost the specifics of the device units being 1 pixel. Could you strengthen that part? Super minor: the diff looks like there are now two periods at the end. That may be weirdness in how the diff is presented, but something to take a quick look at.



> Thank you, @BigB9898 . How you've rephrased this is better than the original, but I'm worried that we lost the specifics of the device units being 1 pixel. Could you strengthen that part? Super minor: the diff looks like there are now two periods at the end. That may be weirdness in how the diff is presented, but something to take a quick look at.

Tyler, I updated per your feedback...Thank you.  Regarding the extra ".", when I previewed it was not there.

**Comment by PRMerger12** [comment]
@BigB9898 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by BigB9898** [comment]
> Thank you, @BigB9898. This looks good. If you could fix the grammar, we'll be good to go. I'd put a period after "...that the pen is used for." and change "resulting in the width to be always 1 pixel." => "That is, the width will always be 1 pixel."

Thanks much!  Updated.

**Comment by PRMerger7** [comment]
@BigB9898 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by BigB9898** [comment]
> We are almost there! Thank you very much for improving the docs. There is one instance of "resulting in the width to be always 1 pixel" If you make that match what you did on line 180, that would be much better and then we can merge this.

@TylerMSFT, thanks...Sorry I missed that update.

**Review by TylerMSFT — APPROVED** [review]
@BigB9898 , thank you for this update. It'll get merged and should hopefully be live by tomorrow.
Really appreciate you taking the time to do this. I know that you are doing it on your own time and just to file down a rough spot in the world to make it a little better place. Thank you.

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
