### PR TITLE
Fix incorrect quotation marks in `Inline functions (C++)`

### PR DESCRIPTION
**Pull request by codeworm96**
This PR fixes incorrect quotation marks in `Inline functions (C++)`:

- "a," -> "a",
- "z." -> "z".

### CODE REVIEW

**Review by orcmid — CHANGES_REQUESTED** [review]
@codeworm96 
LOL.  This is not the place for the American practice of putting the punctuation inside the close-quote.  Good catch!

However, this will also work better if the double-quotes are replaced by single quotes as code literals, since we are talking about single **char** values (i.e.,  `'a'` and `'z'`) eliminating any grammar disagreement.

**Comment by Court72** [comment]
@TylerMSFT

Can you review the proposed changes and [this comment](https://github.com/MicrosoftDocs/cpp-docs/pull/4829#pullrequestreview-1747359947) from @orcmid? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — APPROVED** [review]
How funny. This may have been done by someone who was slavishly following suggestions from our grammar tooling, who didn't understand the context.
Thanks for fixing this.

**Review by TylerMSFT — APPROVED** [review]

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
