### PR TITLE
Repo sync for protected CLA branch

### PR DESCRIPTION
**Pull request by opbld16**
The pull request is created from main637922167238454474 to main to fix git push error for protected CLA branch

### CODE REVIEW

**Comment by PRMerger20** [comment]
@opbld16 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by Jak-MS** [comment]
IMPORTANT: When this content is ready to merge, the reviewer must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by corob-msft — APPROVED** [review]

**Comment by PRMerger-2** [comment]
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Changed Files | This PR contains more than 10 changed files.
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Pull request merged**
