### PR TITLE
Update x64-calling-convention.md

### PR DESCRIPTION
**Pull request by wesinator**
syntax highlighting example return values code

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@TylerMSFT

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — CHANGES_REQUESTED** [review]
Hi, we use output when showing the output of a running program. That's not the case here. These examples are demonstrating types/functions. cpp is the right tag here.

**Review by TylerMSFT — APPROVED** [review]
Thank you for fixing the stragglers in this file.

**Comment by TylerMSFT** [comment]
#sign-off

**Comment by TylerMSFT** [comment]
@wesinator , love your alias tagline, by the way. Thanks for improving this topic today, one PR at a time :-)

**Pull request merged**
