### PR TITLE
Update compiler-warning-level-4-c4464.md

### PR DESCRIPTION
**Pull request by bradlitterell**
@corob-msft 
proposal.  I don't warrant it shouldn't be worded in a better way.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@corob-msft 
- Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by bradlitterell** [comment]
@Jak-MS Are you saying I need to add the #sign-off in a comment, or @corob-msft  does? Thanks,

**Comment by Jak-MS** [comment]
@bradlitterell - @corob-msft  will need to sign off after he reviews the pr. Thanks.

**Comment by bradlitterell** [comment]
thanks a bunch!

**Pull request merged**
