### PR TITLE
Add ARM64 as valid target machine

### PR DESCRIPTION
**Pull request by janisozaur**

### CODE REVIEW

**Comment by PRMerger5** [comment]
@janisozaur : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
#label:"aq-pr-triaged"

**Comment by janisozaur** [comment]
Should `ARM64EC` also be added? https://devblogs.microsoft.com/cppblog/arm64ec-support-in-visual-studio/

**Comment by PRMerger17** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by corob-msft** [comment]
@janisozaur 
Thanks for the update. As far as I can tell, the options available are `ARM`, `ARM64`, `ARM64EC`, `ARM64X`, `EBC`, `X64`, and `X86`. However, I can't find specific information on ARM64X. It appears to create a hybrid ARM64/x86 PE, referred to in some places as a CHPE. It's possible that ARM64X isn't the usual name, which is why I'm not finding much more info.

**Review by corob-msft — APPROVED** [review]

**Pull request merged**
