### PR TITLE
fixed issue #2169

### PR DESCRIPTION
**Pull request by KishkinJ10**
Sir I am a beginner and I tried fixing this issue.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@KishkinJ10 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@KishkinJ10 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@corob-msft Could you take another look? Thanks.

**Comment by PRMerger17** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by corob-msft — APPROVED** [review]
@KishkinJ10 Thanks for the update! You've now joined our list of contributors.

**Pull request merged**
