### PR TITLE
Update ios-functions.md fix typo

### PR DESCRIPTION
**Pull request by pea-sys**
showps→showpos

### CODE REVIEW

**Comment by PRMerger17** [comment]
@pea-sys : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@TylerMSFT 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — APPROVED** [review]
@pea-sys - thank you for fixing the typo and improving the docs!

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
