### PR TITLE
typo in code example

### PR DESCRIPTION
**Pull request by sudoerChris**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@sudoerChris : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by TylerMSFT** [comment]
@sudoerchris, sorry for the hassle on the license thing. Could you give signing the CLA page another go? Would love to get your changes in.

**Comment by PRMerger16** [comment]
@TylerMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sudoerChris** [comment]
@TylerMSFT done, thx for your help!

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ktoliver — APPROVED** [review]

**Comment by TylerMSFT** [comment]
Thank you @ktoliver and @sudoerChris for getting this through. Sorry about the CLA friction.

**Pull request merged**
