### PR TITLE
Fixes #1948

### LINKED ISSUE #1948: Opening an open buffer
It is undocumented that opening a file buffer that is already open fails.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 988d0f9c-053a-5af7-67af-5adaa4dac2c4
* Version Independent ID: 2660e94d-c65f-cf03-4962-d8ba29338567
* Content: [basic_filebuf Class](https://docs.microsoft.com/en-us/cpp/standard-library/basic-filebuf-class?view=vs-2019#feedback)
* Content Source: [docs/standard-library/basic-filebuf-class.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/standard-library/basic-filebuf-class.md)
* Product: **visual-cpp**
* Technology: **cpp-standard-libraries**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

### PR DESCRIPTION
**Pull request by yecril71pl**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@yecril71pl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @corob-msft & @TylerMSFT - Could you review the proposed additions to the content? I don't know whether, if approved, the commit would need to be moved to the private repo for staging before being merged. (It seems like it might not be needed for a new .yml file...) Thanks.

**Comment by TylerMSFT** [comment]
@yecril71pl, could you remove the change to .github/workflows/blank.yml.
It's a small nit, but our style guidelines for voice/tone are to use contractions. Could you modify 'is not' to be: isn't.
Then I'll be happy to approve this change.

**Comment by PRMerger20** [comment]
@yecril71pl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
