### PR TITLE
Standardize See also sections

### PR DESCRIPTION
**Pull request by NextTurn**
Get ready for the following PR.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@NextTurn : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by corob-msft** [comment]
@NextTurn Thanks for spotting and fixing the link formatting typos. This is a good start, and we appreciate your response to the mistakes we made. One of our mistakes was, `## See also` sections should only occur once at the end of an article, not multiple times in the middle, as was done in these when they were merged from multiple sources. If you feel up to moving and merging the `## See also` sections (note sentence-style capitalization) into a single section at the end of the article, then by all means, continue. You'll have our gratitude.

**Comment by PRMerger16** [comment]
@NextTurn : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by NextTurn** [comment]
Thanks for your quick reply @corob-msft. I've merged the sections in the middle into one, and I'll fix the rest in the next PR.

I spotted some `[label](#anchor)` self-referencing links, which may be redundant now.

**Comment by PRMerger15** [comment]
@corob-msft : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@corob-msft : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@corob-msft : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by corob-msft** [comment]
@NextTurn Only one thing left - sign the CLA agreement for these changes to be merged.

**Comment by corob-msft** [comment]
Hmm, curious. Could I have done something to it by contributing the patches? I'll see what I can find out.

**Comment by PRMerger15** [comment]
@corob-msft : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by NextTurn** [comment]
Done by reopening!

**Comment by corob-msft** [comment]
I should have tried that; it's fixed other issues before. Thanks for dealing with it.

**Pull request merged**
