### PR TITLE
Visual C++ 17.0 has unlimited string literals

### PR DESCRIPTION
**Pull request by fsb4000**
I believe this was changed while fixing https://developercommunity.visualstudio.com/t/1437715
@cdacamar knows for sure.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@fsb4000 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@corob-msft 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by cdacamar** [comment]
There are two independent feedback issues we fixed to address the string size limitation:

https://developercommunity.visualstudio.com/t/__FUNCTIONW__-cannot-handle-long-names-a/1425758
https://developercommunity.visualstudio.com/t/Long-literal-char-arrays-are-not-interpr/1374615

In both cases, after 17.0, the compiler has no limitation on string length emission.  The only remaining limitation is in how large of a string literal the preprocessor can handle--which is not currently documented.

**Comment by PRMerger4** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by corob-msft — APPROVED** [review]
@fsb4000 Thanks for being patient; this change is good to go.

**Comment by fsb4000** [comment]
Great! Thanks!

**Pull request merged**
