### PR TITLE
Update conversions-from-floating-point-types.md

### PR DESCRIPTION
**Pull request by prjoseph**
Updating the floating point type conversions document for 16.0 / VS2019.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@prjoseph : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@corob-msft Is this PR ready to merge? Thanks.

**Comment by corob-msft** [comment]
@ktoliver 
This version is out of sync with other changes. I'll move it into cpp-docs-pr and work on it there.

**Comment by ktoliver** [comment]
@corob-msft Thanks!

**Pull request closed without merging**
