### PR TITLE
update the result and exception error format.

### PR DESCRIPTION
**Pull request by NADIRHUSSAIN11**
I have updated the result format by '' cout << "Result"<<" of "<< x << oper << y <<" is : "<< result << endl; ''  in ### To fix the "divide by zero" error and ### To call the Calculator class member functions section, so that the user can better understand what kind of operators and operands he used during input process, so if he will get any error regarding operators and operand can be solved easily. The other thing which I have updated is an exception error message ''Math error: Attempted to divide by Zero'' , so that the user can understand what is zero exception error.

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@NADIRHUSSAIN11 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by NADIRHUSSAIN11** [comment]
[NADIRHUSSAIN11:patch-1](https://github.com/MicrosoftDocs/cpp-docs/pull/3820)

**Review by TylerMSFT — APPROVED** [review]

**Comment by TylerMSFT** [comment]
#sign-off

**Comment by NADIRHUSSAIN11** [comment]
Thank you so much @TylerMSFT ✨️

**Pull request merged**
