### PR TITLE
Change "import existing cache" to "open existing cache"

### PR DESCRIPTION
**Pull request by esweet431**
In Visual Studio 2019 we have support for "opening an existing cache", which operates with the existing cache in place rather than duplicating it. I've updated this section and linked to Will's blog post for more information.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@esweet431 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by esweet431** [comment]
It seems like this PR dup'd my other PR, which had a few minor changes to the "Installation" and "IDE integration" sections

**Comment by corob-msft** [comment]
@esweet431 
It probably looks like a you're reverting changes because the public repo master branch now has your previous changes applied, but your new changes may have been based on the state of master from before those changes. You could merge master into your patch-10 branch, or maybe just copy your latest changes and apply them again on the current public version of the article. It's possible that the merge can figure it out and do the right thing, too.

**Comment by corob-msft** [comment]
@esweet431 
Do you mean to close this PR in favor of #1601 instead?

**Comment by esweet431** [comment]
@corob-msft I think I few changes are in this PR only. I can either close this PR and make the final edits once the changes are live, or we can merge this PR and hope the merge will do the right thing.

**Comment by jborsecnik** [comment]
Note that there's a merge conflict here that would have to be resolved before we could merge.

**Comment by PRMerger19** [comment]
@esweet431 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by esweet431** [comment]
Just resolved, thanks.

**Comment by corob-msft** [comment]
@esweet431 
Erika, before I approve this, take a look at the [file view](https://github.com/MicrosoftDocs/cpp-docs/pull/1600/files) diff. It looks like the first four diff sections undo changes you made in #1598 and #1599. I want to make sure that is your intent before approving and merging this PR.

**Comment by PRMerger6** [comment]
@esweet431 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
