### PR TITLE
Remove duplicate links

### PR DESCRIPTION
**Pull request by NextTurn**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@NextTurn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
confirmed correction

**Comment by jborsecnik** [comment]
confirmed fix  #sign-off

**Comment by PRMerger10** [comment]
@jborsecnik: I'm sorry - only the author of this article, @corob-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by jborsecnik** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@jborsecnik: I'm sorry - only the author of this article, @corob-msft, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
