### PR TITLE
Standardize See also sections

### PR DESCRIPTION
**Pull request by NextTurn**
In *docs/error-messages* directory

### CODE REVIEW

**Comment by PRMerger19** [comment]
@NextTurn : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@corob-msft - can you provide guidance on this PR? thanks!

**Comment by corob-msft** [comment]
@Jak-MS Waiting for some TOC reorg work to land before approving these changes.

**Comment by corob-msft** [comment]
@NextTurn Thanks, see note in #853.

**Pull request closed without merging**
