### PR TITLE
Update how-to-convert-between-various-string-types.md

### PR DESCRIPTION
**Pull request by drvoss**
fix typo

### CODE REVIEW

**Comment by PRMerger9** [comment]
@drvoss : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
@corob-msft I've made the changes you requested. Does the PR look OK to merge? Thanks.

**Comment by corob-msft** [comment]
@ktoliver Thanks for moving on this.

**Pull request merged**
