### PR TITLE
Add left-out nullptr for example code in SetValue

### PR DESCRIPTION
**Pull request by rtischer8277**
As suggested, SetValue's example code should be checked against nullptr: if( property ) needs to be if( property != nullptr )

### CODE REVIEW

**Comment by Court72** [comment]
@corob-msft 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Court72** [comment]
Trying a close/reopen to clear the stuck *license/cla* check.

**Comment by Court72** [comment]
Trying another close/reopen to clear the stuck *license/cla* check.

**Comment by v-lmcdonald** [comment]
Trying another close/reopen to clear the stuck license/cla check.

**Review by corob-msft — APPROVED** [review]

**Comment by corob-msft** [comment]
Yeah, this will take some work. Sit tight.

**Comment by corob-msft** [comment]
I'm going to wait on the next merge from the private branch before going any further.

**Pull request merged**
