### PR TITLE
Fix git push error for protected CLA branch

### PR DESCRIPTION
**Pull request by fenxu**
The pull request is created from master636807619153565393 to master to fix git push error for protected CLA branch

### CODE REVIEW

**Comment by PRMerger14** [comment]
@Taojunshen : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
the doc doesn't have a listed ms.author. @corob-msft or @Mikejo5000 - can you take a look and sign off if this changes is approved?  thanks.

**Comment by Jak-MS** [comment]
@fenxu, 

Since you're a Microsoft employee. Please make content contributions through the private repository so the content can be staged and validated by the current validation rules.

Read about [working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.

Thank you.

**Comment by corob-msft** [comment]
@Jak-MS In the cpp-docs-pr and cpp-docs repos, the author fields are set at folder level in docfx.json, along with most other common metadata fields. It looks like this may be breaking some automation.

**Comment by Jak-MS** [comment]
@corob-msft - thanks!

**Pull request merged**
