### PR TITLE
Update const-cpp.md

### PR DESCRIPTION
**Pull request by science-enthusiast**
More clarity about extern const in C and C++: declaration, definition etc.

### CODE REVIEW

**Comment by Court72** [comment]
@tylermsft

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Court72** [comment]
#label:"aq-pr-triaged"

**Review by TylerMSFT — APPROVED** [review]
Thank you for these updates. They 'definitely' (pun intended) clarify things ;-)

**Comment by TylerMSFT** [comment]
#sign-off

**Pull request merged**
