### PR TITLE
Fix typo that listed for_each instead of find_if

### PR DESCRIPTION
**Pull request by acminor**
Fixed an example description where the description did not match the example

### CODE REVIEW

**Comment by PRMerger19** [comment]
@acminor : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by acminor** [comment]
We might want to update the exact language of executing on each element. I assume that find_if early exits; however, I do not know the exact specification of find_if in the standard.

For now, I did the simplest fix.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by corob-msft — APPROVED** [review]
@acminor Thanks for spotting the issue and making the fix. We appreciate it!

**Pull request merged**
