### PR TITLE
Create `alignas` specifier page

### PR DESCRIPTION
**Pull request by Rageking8**
There exist a page for [`alignof` Operator](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/alignof-operator.md) but they does not seem to be one for `alignas` Specifier. The other pages that mention `alignas` does not go into enough depth. The page [align cpp](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/align-cpp.md) focuses on the Microsoft specific version `__declspec(align(#))` and is not fully applicable to `alignas`. Page [alignment cpp declarations](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/cpp/alignment-cpp-declarations.md) on the other hand is more about the concept of alignment and lacks coverage of `alignas`. The [C version](https://github.com/MicrosoftDocs/cpp-docs/blob/main/docs/c-language/alignment-c.md) is different from C++ `alignas` and some examples are also lacking.

Some loose ends need to be tied up to prevent duplicated content and to ensure the relevant pages are properly linked.

### CODE REVIEW

**Comment by Court72** [comment]
@Rageking8 - Thanks for your pull request. A member of the content team will review it.

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by TylerMSFT** [comment]
@Rageking8 , thank you for taking time to improve the docs! Really appreciate it!
I am working to a deadline this week, so won't be able to look at this until next Monday.
One thing we'll have to sort out is that we don't add content from the public repo. It doesn't have any of our validation/staging/lint tools. So I'll have to port it by hand to the private repo.  What I'll do when I come up for air next Monday is review this with you in the public repo. Once we are happy with it, I'll port it to the private repo so it can get into our publishing system.
Again, thank you so much for contributing to the docs!

**Comment by Rageking8** [comment]
> @Rageking8 , thank you for taking time to improve the docs! Really appreciate it! I am working to a deadline this week, so won't be able to look at this until next Monday. One thing we'll have to sort out is that we don't add content from the public repo. It doesn't have any of our validation/staging/lint tools. So I'll have to port it by hand to the private repo. What I'll do when I come up for air next Monday is review this with you in the public repo. Once we are happy with it, I'll port it to the private repo so it can get into our publishing system. Again, thank you so much for contributing to the docs!

No worries, there is no rush for review and you can always review at the pace you desire. Thanks for the heads up on the publishing process (did not know that it requires more heavy lifting to publish versus just edits)! Happy to review together once you are free.

**Comment by TylerMSFT** [comment]
@Rageking8, I'm coming back around to this. I'd like to take this content, but I want you to get credit for it. I'm not sure how to do that when I port it to our private repo. Let me see if I can figure anything out about that before I do anything.

**Comment by TylerMSFT** [comment]
@rageking8, I've asked around and don't have a good solution for assigning you credit. What I think I'll do is add your public repo fork as a remote to my local private repo and fetch your branch and use it to create a PR in the private repo that I can submit. You good with that?

**Comment by Rageking8** [comment]
> @rageking8, I've asked around and don't have a good solution for assigning you credit. What I think I'll do is add your public repo fork as a remote to my local private repo and fetch your branch and use it to create a PR in the private repo that I can submit. You good with that?

Sounds great! Even if credit for the article is not properly assigned, I am fine with that too.

Since I am busier now, if you could complete the PRs final stretch, I would highly appreciate it. I will try to help if possible. Thanks.

**Comment by TylerMSFT** [comment]
Very good. I'll probably do this by adding your branch as a remote and getting the PR through that way. We'll see how it goes.

**Comment by TylerMSFT** [comment]
@rageking8, after looking into it more I learned that the preferred approach is to bring your branch over to the private repo, get it to meet our publishing requirements and pass our internal tests, and then publish from the private repo.  So that's what I've done.
I don't know if you can see my PR, but [here it is](https://github.com/MicrosoftDocs/cpp-docs-pr/pull/5089/files)  
I did an edit pass and am doing some final review, at which point I'll get this published.
Thank you for adding a new article to the docs! That's above and beyond and love it.
After I publish, we can close this PR.

**Comment by TylerMSFT** [comment]
Hi @rageking8, I ported these changes to a branch in the private repo, did an edit pass, did a technical review, and got it merged.
The new article will show up [here](https://learn.microsoft.com/cpp/cpp/alignas-specifier) by noon or so tomorrow. Your other changes will show up in the repective articles as well.
I'm closing this since the work is done. Take care and huge thanks for giving us a new doc and updating the others!

**Pull request closed without merging**
