### PR TITLE
Update crt-functions-not-supported-in-universal-windows-platform-apps.md

### PR DESCRIPTION
**Pull request by Jaiganeshkumaran**
Adds information about UWP console apps

### CODE REVIEW

**Comment by PRMerger9** [comment]
@Jaiganeshkumaran : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@ShannonLeavitt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by corob-msft — APPROVED** [review]
@Jaiganeshkumaran 
Thanks for the useful pointer, and for submitting an update. We appreciate it!

**Pull request merged**
