### PR TITLE
Add advanced details about using CMake file-api

### PR DESCRIPTION
**Pull request by jamesdooleymsft**
Add 'Advanced CMake cache troubleshooting' section describing how an external CMake toolset can use the CMake file-api to populate Visual Studio with information specific to your project structure.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@jamesdooleymsft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by esweet431** [comment]
LGTM, thank you @jamesdooleymsft !

**Comment by PRMerger19** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by corob-msft** [comment]
@jamesdooleymsft @esweet431 
I gave this an edit pass for style and simplified some grammar for i18n. Please review to make sure I haven't introduced any errors.

**Review by jamesdooleymsft — COMMENTED** [review]
Grammar edits look good.

**Review by corob-msft — APPROVED** [review]

**Comment by corob-msft** [comment]
@jamesdooleymsft Thanks for contributing!

**Pull request merged**
