### PR TITLE
Break statement documentation fix

### LINKED ISSUE #2254: Slightly incorrect example output
For the second example, it says the output will be this.

In each case:
0123

But it should say this.

In each case:
0
1
2
3

or remove the \n from the example code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6c8aeb7-013d-9049-a57e-409df38ca17e
* Version Independent ID: 09540f27-6045-3a69-327c-9ab810b8733a
* Content: [break Statement (C++)](https://docs.microsoft.com/en-us/cpp/cpp/break-statement-cpp?view=vs-2019)
* Content Source: [docs/cpp/break-statement-cpp.md](https://github.com/Microsoft/cpp-docs/blob/master/docs/cpp/break-statement-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

### PR DESCRIPTION
**Pull request by Omcsesz**
fixes #2254

### CODE REVIEW

**Comment by Court72** [comment]
@TylerMSFT

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — APPROVED** [review]
Thank you for taking the time to fix this!
I did some housecleaning that we typically do when we touch old files.
I also made the output match exactly what someone will see so they don't have to interpret the "in each case" thing because that's not the pattern we typically use.

**Comment by Jak-MS** [comment]
@Omcsesz - looks like the system needs you to complete the instructions in this comment: https://github.com/MicrosoftDocs/cpp-docs/pull/4910#issuecomment-1907010734  before we can proceed. thanks.

cc: @TylerMSFT

**Comment by Omcsesz** [comment]
@microsoft-github-policy-service agree

**Comment by TylerMSFT** [comment]
Thanks, @Omcsesz .
#sign-off

**Pull request merged**
