### PR TITLE
Updated the linter settings image.

### PR DESCRIPTION
**Pull request by MryamGirmay**
I have updated the image for linter setting, so it lines up with the updated setting in Visual Studio. There are some docs that have this image referenced but the image wasn't displaying the right information.

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@TylerMSFT

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by TylerMSFT — APPROVED** [review]
Thank you!

**Comment by TylerMSFT** [comment]
#sign-off

**Comment by MryamGirmay** [comment]
#sign-off

**Comment by TylerMSFT** [comment]
@ShannonLeavitt , the system isn't allowing us to #sign-off.  Do you know what the deal is? I own the docs in this directory.

**Comment by TylerMSFT** [comment]
@ShannonLeavitt , interesting. How would I set the author for an image?

**Comment by ShannonLeavitt** [comment]
@TylerMSFT - I don't think there's a way to do that. Fortunately, image-only PRs are rare; when these PRs pop up we can manually assign and merge them.

**Pull request merged**
