### PR TITLE
Function-call evaluation is context-dependent

### PR DESCRIPTION
**Pull request by yecril71pl**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@yecril71pl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @corob-msft 

Could you review the proposed changes to your article?

Thanks!

**Comment by PRMerger16** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@corob-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
